CREATE TABLE `fiscalRecords` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`entityId` int,
	`projectId` int,
	`transactionId` int,
	`receivableId` int,
	`contactId` int,
	`documentId` int,
	`periodStart` timestamp NOT NULL,
	`description` varchar(220) NOT NULL,
	`recordType` enum('income_invoice','expense_receipt','payment_complement','other') NOT NULL DEFAULT 'other',
	`fiscalReference` varchar(160),
	`scope` enum('personal','business','mixed') NOT NULL DEFAULT 'business',
	`currency` varchar(3) NOT NULL DEFAULT 'MXN',
	`totalCents` int NOT NULL DEFAULT 0,
	`taxableBaseCents` int NOT NULL DEFAULT 0,
	`vatCents` int NOT NULL DEFAULT 0,
	`invoiceIssuedAt` timestamp,
	`collectedAt` timestamp,
	`deductibility` enum('pending','deductible','non_deductible','review') NOT NULL DEFAULT 'pending',
	`reviewStatus` enum('draft','pending_review','reviewed','excluded') NOT NULL DEFAULT 'draft',
	`reviewedByUserId` int,
	`reviewedAt` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fiscalRecords_id` PRIMARY KEY(`id`)
);
