import { boolean, index, int, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 * Extend this file with additional tables as your product grows.
 * Columns use camelCase to match both database fields and generated types.
 */
export const users = mysqlTable("users", {
  /**
   * Surrogate primary key. Auto-incremented numeric value managed by the database.
   * Use this for relations between tables.
   */
  id: int("id").autoincrement().primaryKey(),
  /** Manus OAuth identifier (openId) returned from the OAuth callback. Unique per user. */
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

export const localCredentials = mysqlTable("localCredentials", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull().unique(),
  email: varchar("email", { length: 320 }).notNull().unique(),
  passwordHash: varchar("passwordHash", { length: 255 }).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const passwordResetTokens = mysqlTable("passwordResetTokens", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  tokenHash: varchar("tokenHash", { length: 128 }).notNull().unique(),
  expiresAt: timestamp("expiresAt").notNull(),
  usedAt: timestamp("usedAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const financialProfiles = mysqlTable("financialProfiles", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull().unique(),
  workspaceName: varchar("workspaceName", { length: 140 }),
  currency: varchar("currency", { length: 3 }).notNull().default("MXN"),
  taxRegime: mysqlEnum("taxRegime", ["pfae_general", "resico", "other", "not_applicable"]).notNull().default("not_applicable"),
  exchangeRatePolicy: mysqlEnum("exchangeRatePolicy", ["manual", "manual_confirmed", "unconverted"]).notNull().default("manual"),
  onboardingCompleted: boolean("onboardingCompleted").notNull().default(false),
  onboardingStep: int("onboardingStep").notNull().default(0),
  humanReviewRequired: boolean("humanReviewRequired").notNull().default(true),
  displayName: varchar("displayName", { length: 140 }),
  birthDate: timestamp("birthDate"),
  residenceCity: varchar("residenceCity", { length: 120 }),
  contactEmail: varchar("contactEmail", { length: 320 }),
  avatarKey: varchar("avatarKey", { length: 600 }),
  avatarUrl: varchar("avatarUrl", { length: 1200 }),
  personalProfileConsent: boolean("personalProfileConsent").notNull().default(false),
  residenceCountry: varchar("residenceCountry", { length: 80 }),
  taxResidence: varchar("taxResidence", { length: 120 }),
  householdSize: int("householdSize").notNull().default(1),
  dependents: int("dependents").notNull().default(0),
  minimumLiquidityCents: int("minimumLiquidityCents").notNull().default(0),
  referenceEssentialExpensesCents: int("referenceEssentialExpensesCents").notNull().default(0),
  futureTaxReserveCents: int("futureTaxReserveCents").notNull().default(0),
  futureTaxDueAt: timestamp("futureTaxDueAt"),
  riskTolerance: mysqlEnum("riskTolerance", ["low", "medium_low", "medium", "medium_high", "high"]),
  notes: text("notes"),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const notificationPreferences = mysqlTable("notificationPreferences", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull().unique(),
  inAppEnabled: boolean("inAppEnabled").notNull().default(true),
  calendarEnabled: boolean("calendarEnabled").notNull().default(true),
  documentsEnabled: boolean("documentsEnabled").notNull().default(true),
  debtsEnabled: boolean("debtsEnabled").notNull().default(true),
  reviewsEnabled: boolean("reviewsEnabled").notNull().default(true),
  budgetEnabled: boolean("budgetEnabled").notNull().default(true),
  taxReserveEnabled: boolean("taxReserveEnabled").notNull().default(true),
  telegramEnabled: boolean("telegramEnabled").notNull().default(false),
  telegramScheduleCronTaskUid: varchar("telegramScheduleCronTaskUid", { length: 65 }),
  telegramLastDigestDate: varchar("telegramLastDigestDate", { length: 10 }),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
}, table => [index("notification_preferences_telegram_task_uid_idx").on(table.telegramScheduleCronTaskUid)]);

export const financeNotifications = mysqlTable("financeNotifications", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  type: varchar("type", { length: 40 }).notNull(),
  title: varchar("title", { length: 180 }).notNull(),
  message: text("message").notNull(),
  relatedEntityType: varchar("relatedEntityType", { length: 40 }),
  relatedEntityId: int("relatedEntityId"),
  occurredAt: timestamp("occurredAt").defaultNow().notNull(),
  readAt: timestamp("readAt"),
  dismissedAt: timestamp("dismissedAt"),
});

export const qualityIssueAcknowledgements = mysqlTable("qualityIssueAcknowledgements", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  issueKey: varchar("issueKey", { length: 512 }).notNull(),
  acknowledgedAt: timestamp("acknowledgedAt").defaultNow().notNull(),
});

export const workspaceEntities = mysqlTable("workspaceEntities", {
  id: int("id").autoincrement().primaryKey(),
  ownerId: int("ownerId").notNull(),
  name: varchar("name", { length: 180 }).notNull(),
  shortCode: varchar("shortCode", { length: 32 }),
  countryCode: varchar("countryCode", { length: 2 }).notNull().default("MX"),
  legalForm: mysqlEnum("legalForm", ["individual", "pfae", "sa_de_cv", "sapi", "sl", "llc", "holding", "other"]).notNull().default("individual"),
  status: mysqlEnum("status", ["active", "paused", "inactive", "planned", "dissolved"]).notNull().default("active"),
  functionalCurrency: varchar("functionalCurrency", { length: 3 }).notNull().default("MXN"),
  taxRegime: mysqlEnum("taxRegime", ["pfae_general", "resico", "corporate", "not_applicable", "other"]).notNull().default("not_applicable"),
  startedAt: timestamp("startedAt"),
  plannedConversionAt: timestamp("plannedConversionAt"),
  predecessorEntityId: int("predecessorEntityId"),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const financialProjects = mysqlTable("financialProjects", {
  id: int("id").autoincrement().primaryKey(),
  ownerId: int("ownerId").notNull(),
  entityId: int("entityId").notNull(),
  name: varchar("name", { length: 160 }).notNull(),
  status: mysqlEnum("status", ["active", "paused", "closed", "planned"]).notNull().default("active"),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const exchangeRates = mysqlTable("exchangeRates", {
  id: int("id").autoincrement().primaryKey(),
  ownerId: int("ownerId").notNull(),
  fromCurrency: varchar("fromCurrency", { length: 3 }).notNull(),
  toCurrency: varchar("toCurrency", { length: 3 }).notNull(),
  rateMicros: int("rateMicros").notNull(),
  rateDate: timestamp("rateDate").notNull(),
  source: mysqlEnum("source", ["manual", "confirmed_reference"]).notNull().default("manual"),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const collaborationInvites = mysqlTable("collaborationInvites", {
  id: int("id").autoincrement().primaryKey(),
  ownerId: int("ownerId").notNull(),
  invitedEmail: varchar("invitedEmail", { length: 320 }).notNull(),
  role: mysqlEnum("role", ["manager", "reviewer"]).notNull().default("reviewer"),
  canCreateDrafts: boolean("canCreateDrafts").notNull().default(false),
  canReview: boolean("canReview").notNull().default(true),
  status: mysqlEnum("status", ["invited", "accepted", "revoked"]).notNull().default("invited"),
  invitedByUserId: int("invitedByUserId").notNull(),
  acceptedByUserId: int("acceptedByUserId"),
  acceptedAt: timestamp("acceptedAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const accounts = mysqlTable("accounts", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  entityId: int("entityId"),
  projectId: int("projectId"),
  name: varchar("name", { length: 140 }).notNull(),
  type: mysqlEnum("type", ["cash", "bank", "investment", "pension", "property", "business", "other"]).notNull(),
  scope: mysqlEnum("scope", ["personal", "business", "mixed"]).notNull().default("personal"),
  currency: varchar("currency", { length: 3 }).notNull().default("MXN"),
  currentValueCents: int("currentValueCents").notNull().default(0),
  isLiquid: boolean("isLiquid").notNull().default(false),
  valuationDate: timestamp("valuationDate"),
  status: mysqlEnum("status", ["active", "closed"]).notNull().default("active"),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const creditCards = mysqlTable("creditCards", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  entityId: int("entityId"),
  projectId: int("projectId"),
  name: varchar("name", { length: 140 }).notNull(),
  issuer: varchar("issuer", { length: 140 }),
  scope: mysqlEnum("scope", ["personal", "pfae", "business", "mixed"]).notNull().default("personal"),
  currency: varchar("currency", { length: 3 }).notNull().default("MXN"),
  creditLimitCents: int("creditLimitCents").notNull().default(0),
  balanceCents: int("balanceCents").notNull().default(0),
  interestRateBps: int("interestRateBps"),
  minimumPaymentCents: int("minimumPaymentCents").notNull().default(0),
  statementClosingDay: int("statementClosingDay"),
  paymentDueDay: int("paymentDueDay"),
  status: mysqlEnum("status", ["active", "paused", "closed"]).notNull().default("active"),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const financialContacts = mysqlTable("financialContacts", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  entityId: int("entityId"),
  projectId: int("projectId"),
  name: varchar("name", { length: 180 }).notNull(),
  type: mysqlEnum("type", ["client", "supplier", "partner", "friend", "family", "employee", "other"]).notNull().default("other"),
  email: varchar("email", { length: 320 }),
  phone: varchar("phone", { length: 64 }),
  defaultCurrency: varchar("defaultCurrency", { length: 3 }),
  status: mysqlEnum("status", ["active", "paused", "archived"]).notNull().default("active"),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const categories = mysqlTable("categories", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  name: varchar("name", { length: 120 }).notNull(),
  type: mysqlEnum("type", ["income", "expense", "transfer", "mixed"]).notNull().default("mixed"),
  scope: mysqlEnum("scope", ["personal", "business", "mixed"]).notNull().default("personal"),
  isEssential: boolean("isEssential").notNull().default(false),
  isActive: boolean("isActive").notNull().default(true),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const financialTransactions = mysqlTable("financialTransactions", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  entityId: int("entityId"),
  projectId: int("projectId"),
  accountId: int("accountId"),
  categoryId: int("categoryId"),
  goalId: int("goalId"),
  debtId: int("debtId"),
  creditCardId: int("creditCardId"),
  contactId: int("contactId"),
  type: mysqlEnum("type", ["income", "expense", "transfer_out", "transfer_in"]).notNull(),
  scope: mysqlEnum("scope", ["personal", "business", "mixed"]).notNull().default("personal"),
  amountCents: int("amountCents").notNull(),
  currency: varchar("currency", { length: 3 }).notNull().default("MXN"),
  reportCurrency: varchar("reportCurrency", { length: 3 }),
  reportAmountCents: int("reportAmountCents"),
  exchangeRateMicros: int("exchangeRateMicros"),
  exchangeRateDate: timestamp("exchangeRateDate"),
  incomeNature: mysqlEnum("incomeNature", ["business_revenue", "salary_commission", "family_support", "owner_draw", "other"]).notNull().default("other"),
  occurredAt: timestamp("occurredAt").notNull(),
  isEssential: boolean("isEssential").notNull().default(false),
  transferGroupId: varchar("transferGroupId", { length: 64 }),
  status: mysqlEnum("status", ["confirmed", "estimated", "needs_review"]).notNull().default("confirmed"),
  reviewStatus: mysqlEnum("reviewStatus", ["draft", "pending_review", "approved"]).notNull().default("approved"),
  createdByUserId: int("createdByUserId"),
  reviewedByUserId: int("reviewedByUserId"),
  reviewedAt: timestamp("reviewedAt"),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const receivables = mysqlTable("receivables", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  entityId: int("entityId"),
  projectId: int("projectId"),
  contactId: int("contactId"),
  counterparty: varchar("counterparty", { length: 180 }).notNull(),
  origin: varchar("origin", { length: 220 }).notNull(),
  scope: mysqlEnum("scope", ["personal", "business", "mixed"]).notNull().default("personal"),
  amountCents: int("amountCents").notNull(),
  currency: varchar("currency", { length: 3 }).notNull().default("MXN"),
  issuedAt: timestamp("issuedAt").notNull(),
  dueAt: timestamp("dueAt"),
  paidAt: timestamp("paidAt"),
  status: mysqlEnum("status", ["pending", "overdue", "paid", "reconciled"]).notNull().default("pending"),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const receivablePayments = mysqlTable("receivablePayments", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  receivableId: int("receivableId").notNull(),
  linkedTransactionId: int("linkedTransactionId"),
  amountCents: int("amountCents").notNull(),
  currency: varchar("currency", { length: 3 }).notNull().default("MXN"),
  paidAt: timestamp("paidAt").notNull(),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const fiscalRecords = mysqlTable("fiscalRecords", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  entityId: int("entityId"),
  projectId: int("projectId"),
  transactionId: int("transactionId"),
  receivableId: int("receivableId"),
  contactId: int("contactId"),
  documentId: int("documentId"),
  periodStart: timestamp("periodStart").notNull(),
  description: varchar("description", { length: 220 }).notNull(),
  recordType: mysqlEnum("recordType", ["income_invoice", "expense_receipt", "payment_complement", "other"]).notNull().default("other"),
  fiscalReference: varchar("fiscalReference", { length: 160 }),
  scope: mysqlEnum("scope", ["personal", "business", "mixed"]).notNull().default("business"),
  currency: varchar("currency", { length: 3 }).notNull().default("MXN"),
  totalCents: int("totalCents").notNull().default(0),
  taxableBaseCents: int("taxableBaseCents").notNull().default(0),
  vatCents: int("vatCents").notNull().default(0),
  invoiceIssuedAt: timestamp("invoiceIssuedAt"),
  collectedAt: timestamp("collectedAt"),
  deductibility: mysqlEnum("deductibility", ["pending", "deductible", "non_deductible", "review"]).notNull().default("pending"),
  reviewStatus: mysqlEnum("reviewStatus", ["draft", "pending_review", "reviewed", "excluded"]).notNull().default("draft"),
  reviewedByUserId: int("reviewedByUserId"),
  reviewedAt: timestamp("reviewedAt"),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const recurringTemplates = mysqlTable("recurringTemplates", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  entityId: int("entityId"),
  projectId: int("projectId"),
  accountId: int("accountId"),
  categoryId: int("categoryId"),
  contactId: int("contactId"),
  name: varchar("name", { length: 180 }).notNull(),
  counterparty: varchar("counterparty", { length: 180 }),
  type: mysqlEnum("type", ["income", "expense"]).notNull().default("expense"),
  scope: mysqlEnum("scope", ["personal", "business", "mixed"]).notNull().default("personal"),
  amountCents: int("amountCents").notNull(),
  currency: varchar("currency", { length: 3 }).notNull().default("MXN"),
  incomeNature: mysqlEnum("incomeNature", ["business_revenue", "salary_commission", "family_support", "owner_draw", "other"]).notNull().default("other"),
  cadence: mysqlEnum("cadence", ["weekly", "monthly", "quarterly", "annual"]).notNull().default("monthly"),
  nextOccurrenceAt: timestamp("nextOccurrenceAt"),
  status: mysqlEnum("status", ["active", "paused"]).notNull().default("active"),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const payables = mysqlTable("payables", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  entityId: int("entityId"),
  projectId: int("projectId"),
  contactId: int("contactId"),
  creditor: varchar("creditor", { length: 180 }).notNull(),
  origin: varchar("origin", { length: 220 }).notNull(),
  scope: mysqlEnum("scope", ["personal", "business", "mixed"]).notNull().default("personal"),
  amountCents: int("amountCents").notNull(),
  currency: varchar("currency", { length: 3 }).notNull().default("MXN"),
  issuedAt: timestamp("issuedAt").notNull(),
  dueAt: timestamp("dueAt"),
  paidAt: timestamp("paidAt"),
  status: mysqlEnum("status", ["pending", "overdue", "paid", "reconciled"]).notNull().default("pending"),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const payablePayments = mysqlTable("payablePayments", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  payableId: int("payableId").notNull(),
  linkedTransactionId: int("linkedTransactionId"),
  amountCents: int("amountCents").notNull(),
  currency: varchar("currency", { length: 3 }).notNull().default("MXN"),
  paidAt: timestamp("paidAt").notNull(),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const investments = mysqlTable("investments", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  entityId: int("entityId"),
  projectId: int("projectId"),
  name: varchar("name", { length: 180 }).notNull(),
  type: mysqlEnum("type", ["savings", "fixed_income", "fund_etf", "stock", "crypto", "land", "property", "business_equity", "retirement", "other"]).notNull().default("savings"),
  institution: varchar("institution", { length: 180 }),
  scope: mysqlEnum("scope", ["personal", "business", "mixed"]).notNull().default("personal"),
  currency: varchar("currency", { length: 3 }).notNull().default("MXN"),
  costBasisCents: int("costBasisCents").notNull().default(0),
  currentValueCents: int("currentValueCents").notNull().default(0),
  reportCurrency: varchar("reportCurrency", { length: 3 }),
  reportValueCents: int("reportValueCents"),
  exchangeRateMicros: int("exchangeRateMicros"),
  exchangeRateDate: timestamp("exchangeRateDate"),
  valuationDate: timestamp("valuationDate"),
  includeInNetWorth: boolean("includeInNetWorth").notNull().default(true),
  status: mysqlEnum("status", ["active", "paused", "closed"]).notNull().default("active"),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const investmentOperations = mysqlTable("investmentOperations", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  investmentId: int("investmentId").notNull(),
  linkedTransactionId: int("linkedTransactionId"),
  type: mysqlEnum("type", ["contribution", "withdrawal", "yield", "valuation_adjustment"]).notNull(),
  amountCents: int("amountCents").notNull(),
  currency: varchar("currency", { length: 3 }).notNull().default("MXN"),
  occurredAt: timestamp("occurredAt").notNull(),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const financeDocuments = mysqlTable("financeDocuments", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  entityId: int("entityId"),
  projectId: int("projectId"),
  name: varchar("name", { length: 180 }).notNull(),
  type: mysqlEnum("type", ["statement", "invoice", "contract", "policy", "tax", "receipt", "other"]).notNull().default("other"),
  documentClass: varchar("documentClass", { length: 48 }).notNull().default("general"),
  scope: mysqlEnum("scope", ["personal", "business", "mixed"]).notNull().default("personal"),
  relatedEntityType: varchar("relatedEntityType", { length: 32 }).notNull().default("none"),
  relatedEntityId: int("relatedEntityId"),
  jurisdiction: varchar("jurisdiction", { length: 120 }),
  referenceUrl: text("referenceUrl"),
  referenceProvider: mysqlEnum("referenceProvider", ["google_drive", "url", "other"]).notNull().default("url"),
  issuedAt: timestamp("issuedAt"),
  expiresAt: timestamp("expiresAt"),
  reminderAt: timestamp("reminderAt"),
  verified: boolean("verified").notNull().default(false),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const calendarEvents = mysqlTable("calendarEvents", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  entityId: int("entityId"),
  projectId: int("projectId"),
  title: varchar("title", { length: 180 }).notNull(),
  eventType: mysqlEnum("eventType", ["tax", "credit_card_cutoff", "credit_card_payment", "loan_payment", "document_expiry", "insurance_renewal", "review", "other"]).notNull().default("other"),
  scope: mysqlEnum("scope", ["personal", "business", "mixed"]).notNull().default("personal"),
  startsAt: timestamp("startsAt").notNull(),
  endsAt: timestamp("endsAt"),
  recurrence: mysqlEnum("recurrence", ["none", "monthly", "quarterly", "yearly"]).notNull().default("none"),
  amountCents: int("amountCents"),
  currency: varchar("currency", { length: 3 }).notNull().default("MXN"),
  linkedDebtId: int("linkedDebtId"),
  linkedDocumentId: int("linkedDocumentId"),
  linkedTaskId: int("linkedTaskId"),
  status: mysqlEnum("status", ["planned", "completed", "cancelled"]).notNull().default("planned"),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const calendarColorPreferences = mysqlTable("calendarColorPreferences", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  category: mysqlEnum("category", ["tax", "credit_card_cutoff", "credit_card_payment", "loan_payment", "document_expiry", "insurance_renewal", "review", "other", "debt_due", "document_due", "task_due", "fiscal_reserve"]).notNull(),
  colorKey: mysqlEnum("colorKey", ["teal", "emerald", "sky", "indigo", "violet", "amber", "orange", "rose", "slate"]).notNull().default("teal"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const monthlyFinancialStatements = mysqlTable("monthlyFinancialStatements", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  entityId: int("entityId"),
  projectId: int("projectId"),
  filterCurrency: varchar("filterCurrency", { length: 3 }),
  filterReviewStatus: mysqlEnum("filterReviewStatus", ["draft", "pending_review", "approved"]),
  periodStart: timestamp("periodStart").notNull(),
  scope: mysqlEnum("scope", ["personal", "business", "mixed"]).notNull().default("personal"),
  status: mysqlEnum("status", ["draft", "closed"]).notNull().default("draft"),
  incomeCents: int("incomeCents").notNull().default(0),
  expenseCents: int("expenseCents").notNull().default(0),
  netCashFlowCents: int("netCashFlowCents").notNull().default(0),
  assetCents: int("assetCents").notNull().default(0),
  liabilityCents: int("liabilityCents").notNull().default(0),
  netWorthCents: int("netWorthCents").notNull().default(0),
  liquidCents: int("liquidCents").notNull().default(0),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const budgets = mysqlTable("budgets", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  entityId: int("entityId"),
  projectId: int("projectId"),
  categoryId: int("categoryId"),
  scope: mysqlEnum("scope", ["personal", "business", "mixed"]).notNull().default("personal"),
  periodStart: timestamp("periodStart").notNull(),
  plannedCents: int("plannedCents").notNull(),
  type: mysqlEnum("type", ["income", "expense", "savings", "investment"]).notNull().default("expense"),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export const debts = mysqlTable("debts", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  entityId: int("entityId"),
  projectId: int("projectId"),
  contactId: int("contactId"),
  name: varchar("name", { length: 140 }).notNull(),
  creditor: varchar("creditor", { length: 140 }),
  type: mysqlEnum("type", ["credit_card", "loan", "financed_purchase", "mortgage", "tax", "business", "family", "other"]).notNull().default("other"),
  scope: mysqlEnum("scope", ["personal", "business", "mixed"]).notNull().default("personal"),
  balanceCents: int("balanceCents").notNull().default(0),
  originalAmountCents: int("originalAmountCents"),
  installmentCents: int("installmentCents"),
  installmentCount: int("installmentCount"),
  financedItem: varchar("financedItem", { length: 180 }),
  purchasedAt: timestamp("purchasedAt"),
  currency: varchar("currency", { length: 3 }).notNull().default("MXN"),
  interestRateBps: int("interestRateBps"),
  minimumPaymentCents: int("minimumPaymentCents").notNull().default(0),
  nextDueAt: timestamp("nextDueAt"),
  endDate: timestamp("endDate"),
  priority: mysqlEnum("priority", ["critical", "high", "medium", "low"]).notNull().default("medium"),
  status: mysqlEnum("status", ["active", "paid", "review"]).notNull().default("active"),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const debtPayments = mysqlTable("debtPayments", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  debtId: int("debtId").notNull(),
  linkedTransactionId: int("linkedTransactionId"),
  totalPaymentCents: int("totalPaymentCents").notNull(),
  principalCents: int("principalCents").notNull(),
  currency: varchar("currency", { length: 3 }).notNull().default("MXN"),
  paidAt: timestamp("paidAt").notNull(),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const financialGoals = mysqlTable("financialGoals", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  entityId: int("entityId"),
  projectId: int("projectId"),
  name: varchar("name", { length: 160 }).notNull(),
  type: mysqlEnum("type", ["emergency", "debt", "housing", "retirement", "investment", "education", "business", "other"]).notNull().default("other"),
  scope: mysqlEnum("scope", ["personal", "business", "mixed"]).notNull().default("personal"),
  targetCents: int("targetCents").notNull(),
  currentCents: int("currentCents").notNull().default(0),
  monthlyContributionCents: int("monthlyContributionCents").notNull().default(0),
  currency: varchar("currency", { length: 3 }).notNull().default("MXN"),
  targetDate: timestamp("targetDate"),
  priority: mysqlEnum("priority", ["critical", "high", "medium", "low"]).notNull().default("medium"),
  status: mysqlEnum("status", ["active", "paused", "achieved", "cancelled"]).notNull().default("active"),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const financeTasks = mysqlTable("financeTasks", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  entityId: int("entityId"),
  projectId: int("projectId"),
  title: varchar("title", { length: 180 }).notNull(),
  area: mysqlEnum("area", ["budget", "debt", "savings", "investment", "tax", "documents", "business", "review", "other"]).notNull().default("other"),
  scope: mysqlEnum("scope", ["personal", "business", "mixed"]).notNull().default("personal"),
  priority: mysqlEnum("priority", ["critical", "high", "medium", "low"]).notNull().default("medium"),
  status: mysqlEnum("status", ["pending", "in_progress", "waiting", "completed", "cancelled"]).notNull().default("pending"),
  dueAt: timestamp("dueAt"),
  goalId: int("goalId"),
  debtId: int("debtId"),
  requiresConfirmation: boolean("requiresConfirmation").notNull().default(false),
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const monthlyReviews = mysqlTable("monthlyReviews", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  entityId: int("entityId"),
  periodStart: timestamp("periodStart").notNull(),
  status: mysqlEnum("status", ["draft", "reviewed", "closed"]).notNull().default("draft"),
  incomeCents: int("incomeCents").notNull().default(0),
  expenseCents: int("expenseCents").notNull().default(0),
  netCashFlowCents: int("netCashFlowCents").notNull().default(0),
  observations: text("observations"),
  nextActions: text("nextActions"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const decisionRecords = mysqlTable("decisionRecords", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  entityId: int("entityId"),
  projectId: int("projectId"),
  title: varchar("title", { length: 180 }).notNull(),
  area: mysqlEnum("area", ["budget", "debt", "savings", "investment", "tax", "insurance", "assets", "other"]).notNull().default("other"),
  status: mysqlEnum("status", ["proposal", "approved", "reviewed", "discarded"]).notNull().default("proposal"),
  dataUsed: text("dataUsed"),
  assumptions: text("assumptions"),
  risks: text("risks"),
  alternatives: text("alternatives"),
  approvedAction: text("approvedAction"),
  reviewAt: timestamp("reviewAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export const privacyConsents = mysqlTable("privacyConsents", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  purpose: varchar("purpose", { length: 120 }).notNull(),
  accepted: boolean("accepted").notNull(),
  policyVersion: varchar("policyVersion", { length: 40 }).notNull(),
  acceptedAt: timestamp("acceptedAt").defaultNow().notNull(),
});
