import type { ReactNode } from "react";
import { MoneyText } from "@/components/MoneyText";
import { Button } from "@/components/ui/button";
import { formatDate, formatMoney, priorityLabel, scopeLabel } from "@/lib/finance";
import { isMonthlyClosingPending } from "@/lib/monthlyClosing";
import { displayAmountCents } from "@/lib/amountTone";
import { trpc } from "@/lib/trpc";
import { dashboardPeriodQuery } from "@/lib/dashboardPeriod";
import { emptyWorkspaceFilters, filterWorkspaceSnapshot, WorkspaceFilterBar } from "@/components/WorkspaceFilterBar";
import { buildPfaePanelSummary } from "../../../shared/pfaePanelSummary";
import { creditCardUtilizationAlerts } from "../../../shared/creditCardSummary";
import { AlertTriangle, ArrowDownLeft, ArrowUpRight, CalendarClock, CheckCircle2, CircleDollarSign, Landmark, ListTodo, Plus, ReceiptText, ShieldCheck, Target, WalletCards } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";

function MetricCard({ icon: Icon, label, value, note, tone = "neutral" }: { icon: typeof WalletCards; label: string; value: ReactNode; note: ReactNode; tone?: "neutral" | "positive" | "warm" | "danger" }) {
  return <article className={`metric-card metric-${tone}`}><div className="metric-icon"><Icon className="size-5" /></div><p>{label}</p><strong>{value}</strong><small>{note}</small></article>;
}

export default function Home() {
  const { data: rawData, isLoading, error } = trpc.finance.dashboard.useQuery(dashboardPeriodQuery);
  const { data: notificationData } = trpc.finance.notifications.get.useQuery(undefined, { staleTime: 60_000 });
  const [workspaceFilters, setWorkspaceFilters] = useState(emptyWorkspaceFilters);
  const data = useMemo(() => {
    if (!rawData) return rawData;
    const hasFilters = Object.values(workspaceFilters).some(Boolean);
    if (!hasFilters) return rawData;
    const scoped = filterWorkspaceSnapshot(rawData, workspaceFilters);
    const currency = rawData.dashboard.reportCurrency || rawData.profile?.currency || "MXN";
    const start = new Date(rawData.dashboard.periodStart);
    const end = new Date(start.getFullYear(), start.getMonth() + 1, 1);
    const reportAmount = (item: any) => item.reportCurrency === currency && typeof item.reportAmountCents === "number" ? item.reportAmountCents : item.currency === currency ? item.amountCents : null;
    const currentTransactions = scoped.transactions.filter((item: any) => new Date(item.occurredAt) >= start && new Date(item.occurredAt) < end);
    const incomeCents = currentTransactions.filter((item: any) => item.type === "income").reduce((total: number, item: any) => total + (reportAmount(item) ?? 0), 0);
    const expenseCents = currentTransactions.filter((item: any) => item.type === "expense").reduce((total: number, item: any) => total + (reportAmount(item) ?? 0), 0);
    const pendingConversionCount = currentTransactions.filter((item: any) => (item.type === "income" || item.type === "expense") && reportAmount(item) === null).length;
    const accounts = scoped.accounts.filter((item: any) => item.status === "active" && item.currency === currency);
    const debts = scoped.debts.filter((item: any) => (item.status === "active" || item.status === "review") && item.currency === currency);
    const assetCents = accounts.reduce((total: number, item: any) => total + item.currentValueCents, 0);
    const liabilityCents = debts.reduce((total: number, item: any) => total + item.balanceCents, 0);
    const essentialExpensesCents = currentTransactions.filter((item: any) => item.type === "expense" && item.isEssential).reduce((total: number, item: any) => total + (reportAmount(item) ?? 0), 0);
    const liquidCents = accounts.filter((item: any) => item.isLiquid).reduce((total: number, item: any) => total + item.currentValueCents, 0);
    return { ...scoped, dashboard: { ...rawData.dashboard, cashFlow: { incomeCents, expenseCents, netCashFlowCents: incomeCents - expenseCents, pendingConversionCount }, netWorth: { assetCents, liabilityCents, netWorthCents: assetCents - liabilityCents }, liquidity: { liquidCents, coverageMonths: essentialExpensesCents > 0 ? liquidCents / essentialExpensesCents : null }, essentialExpensesCents } } as typeof rawData;
  }, [rawData, workspaceFilters]);
  if (isLoading) return <div className="page-loading">Preparando tu visión financiera…</div>;
  if (error || !data) return <div className="error-state"><AlertTriangle className="size-6" /><h1>No hemos podido cargar tu espacio financiero</h1><p>Inténtalo de nuevo. Tus datos siguen protegidos y no se ha realizado ninguna acción.</p></div>;

  const currency = data.dashboard.reportCurrency ?? data.profile?.currency ?? "MXN";
  const creditAlertThreshold = notificationData?.preferences.creditUtilizationThresholdPercent ?? 20;
  const pendingTasks = data.tasks.filter(task => task.status !== "completed" && task.status !== "cancelled").slice().sort((a, b) => (a.dueAt ? new Date(a.dueAt).getTime() : Infinity) - (b.dueAt ? new Date(b.dueAt).getTime() : Infinity));
  const activeGoals = data.goals.filter(goal => goal.status === "active");
  const activeDebts = data.debts.filter(debt => debt.status === "active" || debt.status === "review");
  const reportCurrencyDebts = activeDebts.filter(debt => debt.currency === currency);
  const debtBalance = reportCurrencyDebts.reduce((total, debt) => total + debt.balanceCents, 0);
  const pendingDebtCurrencyCount = activeDebts.length - reportCurrencyDebts.length;
  const hasData = data.accounts.length + data.transactions.length + data.debts.length + data.goals.length > 0;
  const closingPending = isMonthlyClosingPending(data.statements ?? [], data.dashboard.periodStart);
  const pfaeSummary = buildPfaePanelSummary({ records: data.fiscalRecords ?? [], fiscalReviews: data.fiscalPeriodReviews ?? [], calendarEvents: data.calendarEvents ?? [], periodStart: data.dashboard.periodStart, futureTaxDueAt: data.profile?.futureTaxDueAt });
  const creditUtilizationAlerts = creditCardUtilizationAlerts(data.creditCards ?? [], currency, creditAlertThreshold);

  return <div className="space-y-8">
    <section className="hero-panel">
      <div><p className="eyebrow">Espacio privado · {currency}</p><h1>Decide con claridad.<br /><em>Gestiona con calma.</em></h1><p className="hero-description">Una visión manual, trazable y separada de tus finanzas personales y empresariales. Sin bancos conectados, sin pagos, sin automatismos invisibles.</p></div>
      <div className="hero-aside"><div className="privacy-dot"><ShieldCheck className="size-5" /></div><div><strong>Control total de tus datos</strong><p>Solo analizamos lo que registras en Meximoney.</p></div></div>
    </section>

    <WorkspaceFilterBar snapshot={data} filters={workspaceFilters} onChange={setWorkspaceFilters} />

    {closingPending ? <section className="flex flex-col gap-3 rounded-2xl border border-amber-300 bg-amber-50 px-5 py-4 text-amber-950 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><span className="mt-0.5 rounded-xl bg-amber-200 p-2 text-amber-800"><AlertTriangle className="size-4" /></span><div><p className="font-semibold">Cierre mensual pendiente</p><p className="mt-1 text-sm">Aún no hay un cierre guardado para {formatDate(data.dashboard.periodStart, { month: "long", year: "numeric" })}. Revisa pendientes y confirma el control mensual antes de guardar la fotografía histórica.</p></div></div><Link href="/control-mensual"><Button variant="outline" className="shrink-0 border-amber-400 bg-white text-amber-950 hover:bg-amber-100">Abrir control mensual</Button></Link></section> : null}

    {creditUtilizationAlerts.length ? <section className="rounded-2xl border border-rose-200 bg-rose-50 px-5 py-4 text-rose-950"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-start gap-3"><span className="mt-0.5 rounded-xl bg-rose-100 p-2 text-rose-700"><AlertTriangle className="size-4" /></span><div><p className="font-semibold">Utilización de crédito por encima del {creditAlertThreshold}%</p><p className="mt-1 text-sm text-rose-900">Estas tarjetas ya superan el umbral configurado. Revisa su saldo antes de asumir nuevos cargos.</p></div></div><Link href="/tarjetas" className="shrink-0 text-sm font-semibold text-rose-800 underline-offset-4 hover:underline">Revisar tarjetas</Link></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{creditUtilizationAlerts.slice(0, 6).map(card => <Link href={`/tarjetas#credit-card-${card.id}`} className="flex items-center justify-between gap-3 rounded-xl border border-rose-200 bg-white/70 px-3 py-2.5 transition-colors hover:bg-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-rose-500" key={card.id}><div className="min-w-0"><p className="truncate text-sm font-semibold">{card.name || "Tarjeta sin nombre"}</p><p className="truncate text-xs text-rose-800">{card.issuer || "Entidad no especificada"} · Saldo {formatMoney(card.balanceCents, card.currency)}</p></div><span className="shrink-0 text-sm font-bold text-rose-700">{card.utilizationPercent?.toFixed(1)}%</span></Link>)}</div>{creditUtilizationAlerts.length > 6 ? <p className="mt-3 text-xs text-rose-800">Hay {creditUtilizationAlerts.length - 6} tarjeta(s) adicional(es) por encima del umbral.</p> : null}</section> : null}

    {!hasData ? <section className="onboarding-card"><div><p className="eyebrow">Primeros pasos</p><h2>Construye una base fiable antes de analizar.</h2><p>Registra una cuenta, crea tus categorías y añade tus primeros movimientos. El panel calculará tu situación a partir de datos confirmados.</p></div><div className="onboarding-actions"><Link href="/movimientos"><Button className="btn-primary"><Plus className="size-4" /> Registrar una cuenta</Button></Link><Link href="/movimientos"><Button variant="outline">Añadir movimiento</Button></Link></div></section> : null}

    <section><div className="section-heading"><div><p className="eyebrow">Resumen del periodo · {currency}</p><h2>Tu situación actual</h2></div><span className="period-chip">{formatDate(data.dashboard.periodStart, { month: "long", year: "numeric" })}</span></div><div className="metric-grid"><MetricCard icon={CircleDollarSign} label="Flujo neto" value={<MoneyText cents={data.dashboard.cashFlow.netCashFlowCents} currency={currency} />} note={<><MoneyText cents={data.dashboard.cashFlow.incomeCents} currency={currency} /> ingresos · <MoneyText cents={displayAmountCents(data.dashboard.cashFlow.expenseCents, "expense")} currency={currency} /> gastos</>} tone={data.dashboard.cashFlow.netCashFlowCents >= 0 ? "positive" : "danger"} /><MetricCard icon={Landmark} label="Patrimonio neto" value={<MoneyText cents={data.dashboard.netWorth.netWorthCents} currency={currency} />} note={<><MoneyText cents={data.dashboard.netWorth.assetCents} currency={currency} /> activos · <MoneyText cents={displayAmountCents(data.dashboard.netWorth.liabilityCents, "liability")} currency={currency} /> deudas</>} /><MetricCard icon={WalletCards} label="Liquidez disponible" value={<MoneyText cents={data.dashboard.liquidity.liquidCents} currency={currency} />} note={data.dashboard.liquidity.coverageMonths === null ? "Registra gastos esenciales para estimar cobertura" : `${data.dashboard.liquidity.coverageMonths.toFixed(1)} meses de cobertura estimada`} tone="warm" /><MetricCard icon={CircleDollarSign} label="Deuda activa" value={<MoneyText cents={displayAmountCents(debtBalance, "liability")} currency={currency} />} note={pendingDebtCurrencyCount ? `${reportCurrencyDebts.length} en ${currency} · ${pendingDebtCurrencyCount} pendiente de valorar` : `${activeDebts.length} obligaciones activas o por revisar`} tone={activeDebts.length ? "danger" : "positive"} /></div></section>

    <div className="dashboard-grid">
      <section className="content-card main-card"><div className="card-title-row"><div><h2>Flujo manual del mes</h2><p>Los ingresos y gastos excluyen transferencias internas y usan sólo conversión confirmada a {currency}.</p></div><Link className="text-link" href="/movimientos">Ver movimientos</Link></div><div className="flow-visual"><div className="flow-row"><span><i className="flow-dot dot-income"><ArrowDownLeft className="size-3" /></i>Ingresos</span><strong><MoneyText cents={data.dashboard.cashFlow.incomeCents} currency={currency} /></strong></div><div className="flow-bar"><span className="income-bar" style={{ width: `${data.dashboard.cashFlow.incomeCents > 0 ? 100 : 0}%` }} /></div><div className="flow-row"><span><i className="flow-dot dot-expense"><ArrowUpRight className="size-3" /></i>Gastos</span><strong><MoneyText cents={displayAmountCents(data.dashboard.cashFlow.expenseCents, "expense")} currency={currency} /></strong></div><div className="flow-bar"><span className="expense-bar" style={{ width: `${data.dashboard.cashFlow.incomeCents ? Math.min(100, (data.dashboard.cashFlow.expenseCents / data.dashboard.cashFlow.incomeCents) * 100) : 0}%` }} /></div><div className="flow-footer"><span>Resultado del periodo</span><strong className={data.dashboard.cashFlow.netCashFlowCents >= 0 ? "amount-positive" : "amount-negative"}><MoneyText cents={data.dashboard.cashFlow.netCashFlowCents} currency={currency} /></strong></div>{data.dashboard.cashFlow.pendingConversionCount > 0 ? <div className="mt-4 rounded-lg bg-amber-50 px-3 py-2 text-xs leading-5 text-amber-900"><AlertTriangle className="mr-1 inline size-3.5" />{data.dashboard.cashFlow.pendingConversionCount} {data.dashboard.cashFlow.pendingConversionCount === 1 ? "partida quedó" : "partidas quedaron"} fuera del total hasta confirmar su conversión manual a {currency}.</div> : null}</div></section>
      <section className="content-card"><div className="card-title-row"><div><p className="eyebrow">Preparación fiscal manual</p><h2>Seguimiento PFAE</h2><p>Indicadores registrados para {formatDate(data.dashboard.periodStart, { month: "long", year: "numeric" })}.</p></div><Link className="text-link" href="/fiscal">Abrir Libro</Link></div><div className="mt-5 space-y-3"><div className="rounded-xl bg-amber-50 p-3"><span className="flex items-center gap-2 text-sm font-medium text-amber-950"><ReceiptText className="size-4" /> IVA manual registrado</span><strong className="mt-1 block text-xl text-amber-950"><MoneyText cents={pfaeSummary.vatRegisteredCents} currency={currency} /></strong><small className="mt-1 block text-amber-900">Dato capturado; no es IVA a pagar ni cálculo tributario.</small></div><div className="flex items-start justify-between gap-3 border-b border-border pb-3"><div><strong className="block text-sm">Revisión del periodo</strong><small className="text-muted-foreground">{pfaeSummary.recordCount ? `${pfaeSummary.pendingReviewCount} renglón(es) pendientes de revisión.` : "Sin renglones PFAE registrados en este periodo."}</small></div><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${pfaeSummary.reviewStatus === "reviewed" ? "bg-emerald-500/10 text-emerald-800" : "bg-amber-500/10 text-amber-800"}`}>{pfaeSummary.reviewStatus === "reviewed" ? "Revisado manualmente" : "Rutina abierta"}</span></div><div className="flex items-start gap-3"><CalendarClock className="mt-0.5 size-4 text-primary" /><div><strong className="block text-sm">Próxima fecha fiscal manual</strong><p className="text-sm text-muted-foreground">{pfaeSummary.nextDate ? `${formatDate(pfaeSummary.nextDate)} · ${pfaeSummary.nextDateLabel}` : "Sin fecha fiscal configurada. Regístrala en Calendario o Perfil."}</p></div></div></div></section>
    </div>

    <div className="dashboard-grid">
      <section className="content-card"><div className="card-title-row"><div><h2>Objetivos en marcha</h2><p>Progreso medido con el último valor manual.</p></div><Link href="/planificacion" className="text-link">Gestionar</Link></div>{activeGoals.length === 0 ? <div className="inline-empty"><Target className="size-5" /><span>No hay objetivos activos. Define una meta para convertir prioridades en un plan.</span></div> : <div className="goal-list">{activeGoals.slice(0, 4).map(goal => { const progress = goal.targetCents > 0 ? Math.min(100, (goal.currentCents / goal.targetCents) * 100) : 0; return <div className="goal-row" key={goal.id}><div className="goal-head"><span><strong>{goal.name}</strong><small>{scopeLabel[goal.scope]} · {priorityLabel[goal.priority]}</small></span><b>{progress.toFixed(0)}%</b></div><div className="progress-track"><span style={{ width: `${progress}%` }} /></div><div className="goal-meta"><span><MoneyText cents={goal.currentCents} currency={goal.currency} /> de <MoneyText cents={goal.targetCents} currency={goal.currency} /></span><span>{goal.targetDate ? `Meta: ${formatDate(goal.targetDate)}` : "Fecha pendiente"}</span></div></div>; })}</div>}</section>
      <section className="content-card"><div className="card-title-row"><div><h2>ToDo prioritario</h2><p>Las próximas acciones de todos tus módulos, ordenadas para decidir qué sigue.</p></div><Link href="/todo" className="text-link">Abrir ToDo</Link></div>{pendingTasks.length === 0 ? <div className="inline-empty"><ListTodo className="size-5" /><span>No hay tareas pendientes. Añade una próxima acción desde ToDo o desde su módulo de origen.</span></div> : <div className="task-list">{pendingTasks.slice(0, 4).map(task => <Link href="/todo" className="task-row transition-colors hover:bg-muted/60" key={task.id}><span className={`priority-dot priority-${task.priority}`} /><div><strong>{task.title}</strong><small>{task.dueAt ? `Vence ${formatDate(task.dueAt)}` : "Sin fecha límite"} · {scopeLabel[task.scope]}</small></div><span className="task-priority">{priorityLabel[task.priority]}</span></Link>)}</div>}</section>
    </div>
  </div>;
}
