import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { emptyWorkspaceFilters, filterWorkspaceSnapshot, WorkspaceFilterBar } from "@/components/WorkspaceFilterBar";
import { deriveAccountBalance, balanceSignal } from "@/lib/accountHub";
import { scopeLabel } from "@/lib/finance";
import { exportPatrimonyHistory, type PatrimonyHistoryExportRow } from "@/lib/patrimonyHistoryExport";
import { buildPatrimonyDistribution, type PatrimonyDistributionEntry } from "@/lib/patrimonyDistribution";
import { trpc } from "@/lib/trpc";
import { Building2, Download, FileSpreadsheet, Landmark, PieChart as PieChartIcon, Scale, TrendingDown, TrendingUp, WalletCards } from "lucide-react";
import { CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart as RechartsPieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useMemo, useState } from "react";

const money = (cents: number, currency: string) => new Intl.NumberFormat("es-MX", { style: "currency", currency, minimumFractionDigits: 2 }).format(cents / 100);

type LiveSummary = { assetCents: number; liabilityCents: number; netWorthCents: number };

export default function Patrimony() {
  const { data, isLoading } = trpc.finance.workspace.get.useQuery(undefined, { staleTime: 0, refetchOnMount: "always" });
  const [filters, setFilters] = useState(emptyWorkspaceFilters);
  const snapshot = useMemo(() => data ? filterWorkspaceSnapshot(data, filters) : null, [data, filters]);

  if (isLoading || !data || !snapshot) return <section className="space-y-6"><p className="page-subtitle">Cargando patrimonio privado…</p></section>;

  const totalCurrency = filters.currency || data.dashboard.reportCurrency;
  const accountBalances = snapshot.accounts
    .filter((item: any) => item.status === "active")
    .map((account: any) => ({ account, derived: deriveAccountBalance(account, snapshot.transactions) }));
  const accounts = accountBalances.filter(({ account }: { account: any }) => account.currency === totalCurrency);
  const investments = (snapshot.investments ?? []) as any[];
  const comparableInvestments = investments
    .filter(item => item.includeInNetWorth && item.status !== "closed")
    .map(item => ({ item, value: item.currency === totalCurrency ? item.currentValueCents : !filters.currency && item.reportCurrency === totalCurrency ? item.reportValueCents : null }))
    .filter((row): row is { item: any; value: number } => row.value !== null);
  const financedAssets = ((snapshot.financedAssetPurchases ?? []) as any[])
    .map(purchase => ({ ...purchase, asset: investments.find(item => item.id === purchase.investmentId), debt: snapshot.debts.find((debt: any) => debt.id === purchase.debtId) }))
    .filter(item => item.asset && item.asset.currency === totalCurrency);
  const debts = snapshot.debts.filter((item: any) => (item.status === "active" || item.status === "review") && item.currency === totalCurrency);
  const creditCards = (snapshot.creditCards ?? []).filter((item: any) => item.status !== "closed" && item.currency === totalCurrency);
  const assetCents = accounts.reduce((sum: number, item: any) => sum + item.derived.currentBalanceCents, 0) + comparableInvestments.reduce((sum, row) => sum + row.value, 0);
  const liabilityCents = debts.reduce((sum: number, item: any) => sum + item.balanceCents, 0) + creditCards.reduce((sum: number, item: any) => sum + item.balanceCents, 0);
  const liveSummary: LiveSummary = { assetCents, liabilityCents, netWorthCents: assetCents - liabilityCents };
  const history = snapshot.statements.slice().sort((a: any, b: any) => new Date(a.periodStart).getTime() - new Date(b.periodStart).getTime()).slice(-12);
  const chartData = [
    ...history.map((statement: any) => ({ period: new Date(statement.periodStart).toLocaleDateString("es-MX", { month: "short", year: "2-digit" }), activos: statement.assetCents / 100, pasivos: statement.liabilityCents / 100, patrimonio: statement.netWorthCents / 100, live: false })),
    { period: "Actual", activos: assetCents / 100, pasivos: liabilityCents / 100, patrimonio: liveSummary.netWorthCents / 100, live: true },
  ];
  const scale = Math.max(1, ...history.map((statement: any) => Math.abs(statement.netWorthCents)), Math.abs(liveSummary.netWorthCents));
  const distribution = buildPatrimonyDistribution({ accounts: accounts.map(({ derived }: { derived: ReturnType<typeof deriveAccountBalance> }) => ({ currentBalanceCents: derived.currentBalanceCents })), investments: comparableInvestments.map(row => ({ valueCents: row.value })), debts, creditCards });
  const historyExportRows: PatrimonyHistoryExportRow[] = [
    ...history.map((statement: any) => ({ periodo: new Date(statement.periodStart).toLocaleDateString("es-MX", { month: "short", year: "numeric" }), activos: statement.assetCents / 100, pasivos: statement.liabilityCents / 100, patrimonioNeto: statement.netWorthCents / 100, origen: "Cierre mensual" })),
    { periodo: "Actual", activos: assetCents / 100, pasivos: liabilityCents / 100, patrimonioNeto: liveSummary.netWorthCents / 100, origen: "Cálculo vivo" },
  ];
  const pending = data.dashboard.qualityIssues.filter((issue: any) => (issue.code === "pending_investment_conversion" || issue.code === "stale_investment") && investments.some(item => issue.label.includes(item.name)));

  const accountItems = accountBalances.map(({ account, derived }: { account: any; derived: ReturnType<typeof deriveAccountBalance> }) => {
    const signal = balanceSignal(derived.currentBalanceCents);
    return { id: account.id, name: account.name, subtitle: `${account.type.replaceAll("_", " ")} · ${account.currency}`, amount: money(derived.currentBalanceCents, account.currency), state: account.currency === totalCurrency ? signal.label : "Otra moneda" };
  });

  return <section className="space-y-6">
    <header><p className="eyebrow">Visión consolidada y manual</p><h1 className="page-title">Patrimonio neto</h1><p className="page-subtitle">Activos menos pasivos para la entidad, proyecto y moneda que selecciones. Los saldos de cuentas se derivan de su valoración manual y de movimientos confirmados posteriores.</p></header>
    <WorkspaceFilterBar snapshot={data} filters={filters} onChange={setFilters} showReview={false}/>
    <div className="grid gap-3 sm:grid-cols-3"><Summary icon={Scale} label={`Patrimonio neto · ${totalCurrency}`} value={money(liveSummary.netWorthCents, totalCurrency)} tone={liveSummary.netWorthCents >= 0 ? "positive" : "negative"}/><Summary icon={TrendingUp} label="Activos comparables" value={money(assetCents, totalCurrency)} tone="positive"/><Summary icon={TrendingDown} label="Pasivos comparables" value={money(liabilityCents, totalCurrency)} tone="negative"/></div>
    <HistoryChart data={chartData} currency={totalCurrency}/>
    <PatrimonyDistributionChart entries={distribution.entries} currency={totalCurrency}/>
    <Card className="surface-card"><CardContent className="space-y-2 p-4 text-sm text-muted-foreground"><p>La marca <strong className="text-foreground">Actual</strong> refleja el cálculo vivo de esta consulta: valoración de cada cuenta más movimientos confirmados posteriores, inversiones manuales comparables y pasivos vigentes.</p><p>Los cierres mensuales anteriores son fotografías históricas y permanecen sin sobrescribirse cuando cambian los valores actuales.</p></CardContent></Card>
    {financedAssets.length ? <FinancedAssetList rows={financedAssets} currency={totalCurrency}/> : null}
    <div className="grid gap-4 lg:grid-cols-2"><AssetList title="Cuentas y activos" icon={WalletCards} items={accountItems}/><AssetList title="Ahorro e inversiones" icon={Landmark} items={investments.filter(item => item.status !== "closed").map(item => ({ id: item.id, name: item.name, subtitle: item.institution || item.type.replaceAll("_", " "), amount: money(item.currentValueCents, item.currency), state: comparableInvestments.some(row => row.item.id === item.id) ? "Incluida" : item.includeInNetWorth ? "Conversión pendiente" : "Excluida" }))}/><AssetList title="Pasivos vigentes" icon={Building2} items={[...debts.map((item: any) => ({ id: `debt-${item.id}`, name: item.name, subtitle: item.creditor || item.type.replaceAll("_", " "), amount: money(item.balanceCents, item.currency), state: "Saldo pendiente" })), ...creditCards.map((item: any) => ({ id: `card-${item.id}`, name: item.name, subtitle: `${item.issuer ? `Tarjeta · ${item.issuer}` : "Tarjeta de crédito"} · ${scopeLabel[item.scope] ?? item.scope}`, amount: money(item.balanceCents, item.currency), state: "Saldo pendiente" }))]}/><HistoryCard history={history} currency={totalCurrency} scale={scale} current={liveSummary} exportRows={historyExportRows}/></div>
    {pending.length ? <Card className="surface-card border-amber-300"><CardHeader><CardTitle className="text-base">Valuaciones que requieren revisión</CardTitle><CardDescription>Corrige la posición desde Ahorro e inversiones antes de consolidarla.</CardDescription></CardHeader><CardContent className="space-y-2">{pending.map((issue: any, index: number) => <p key={`${issue.code}-${index}`} className="text-sm text-muted-foreground">{issue.label}</p>)}</CardContent></Card> : null}
  </section>;
}

function Summary({ icon: Icon, label, value, tone }: { icon: any; label: string; value: string; tone: "positive" | "negative" }) { return <Card className="surface-card"><CardContent className="flex items-center gap-3 p-4"><span className={tone === "positive" ? "rounded-xl bg-emerald-500/10 p-2 text-emerald-700" : "rounded-xl bg-rose-500/10 p-2 text-rose-700"}><Icon className="h-4 w-4"/></span><div><p className="text-xs text-muted-foreground">{label}</p><p className="font-semibold">{value}</p></div></CardContent></Card>; }
function FinancedAssetList({ rows, currency }: { rows: any[]; currency: string }) { return <Card className="surface-card"><CardHeader><CardTitle className="text-base">Activos con financiación vinculada</CardTitle><CardDescription>El activo se muestra como valor manual y la deuda como pasivo independiente. La diferencia es el patrimonio neto asociado.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">{rows.map(row => { const equity = row.asset.currentValueCents - (row.debt?.balanceCents ?? 0); return <div key={row.id} className="rounded-xl border border-border/70 p-3"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{row.asset.name}</p><p className="text-xs text-muted-foreground">{row.valuationPolicy === "depreciating" ? "Depreciación manual" : row.valuationPolicy === "appreciating" ? "Apreciación manual" : "Valuación manual"}</p></div><Badge variant="secondary">{row.asset.type === "vehicle" ? "Vehículo" : row.asset.type === "property" ? "Vivienda" : "Activo"}</Badge></div><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><div><p className="text-muted-foreground">Valor</p><strong>{money(row.asset.currentValueCents, currency)}</strong></div><div><p className="text-muted-foreground">Deuda</p><strong>{row.debt ? money(row.debt.balanceCents, currency) : "Sin saldo"}</strong></div><div><p className="text-muted-foreground">Neto</p><strong>{money(equity, currency)}</strong></div></div></div>; })}</CardContent></Card>; }
  function HistoryChart({ data, currency }: { data: { period: string; activos: number; pasivos: number; patrimonio: number; live: boolean }[]; currency: string }) { return <Card className="surface-card"><CardHeader><CardTitle className="text-base">Evolución histórica</CardTitle><CardDescription>Compara tus cierres manuales con el cálculo actual vivo; los cambios actuales se reflejan sin sobrescribir el historial.</CardDescription></CardHeader><CardContent>{data.length < 2 ? <p className="py-10 text-center text-sm text-muted-foreground">Guarda al menos un cierre mensual para comparar la evolución con el valor actual.</p> : <div className="h-72 w-full"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{ left: 8, right: 16, top: 8, bottom: 4 }}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="period" fontSize={12}/><YAxis tickFormatter={value => new Intl.NumberFormat("es-MX", { notation: "compact", style: "currency", currency }).format(value)} fontSize={12} width={76}/><Tooltip formatter={(value: number) => new Intl.NumberFormat("es-MX", { style: "currency", currency }).format(value)} /><Legend/><Line type="monotone" dataKey="activos" name="Activos" stroke="#0f766e" strokeWidth={2} dot={{ r: 3 }}/><Line type="monotone" dataKey="pasivos" name="Pasivos" stroke="#be123c" strokeWidth={2} dot={{ r: 3 }}/><Line type="monotone" dataKey="patrimonio" name="Patrimonio neto" stroke="#1d4ed8" strokeWidth={2.5} dot={{ r: 3 }}/></LineChart></ResponsiveContainer></div>}</CardContent></Card>; }
  function PatrimonyDistributionChart({ entries, currency }: { entries: PatrimonyDistributionEntry[]; currency: string }) { return <Card className="surface-card"><CardHeader><div className="flex items-start gap-3"><span className="rounded-xl bg-primary/10 p-2 text-primary"><PieChartIcon className="size-4" /></span><div><CardTitle className="text-base">Distribución de activos y pasivos</CardTitle><CardDescription>Comparación de los importes consolidados en {currency}. Las monedas no se mezclan.</CardDescription></div></div></CardHeader><CardContent>{entries.length === 0 ? <p className="py-8 text-center text-sm text-muted-foreground">No hay saldos comparables en {currency} para construir la distribución.</p> : <div className="grid gap-4 md:grid-cols-[minmax(0,18rem)_minmax(0,1fr)] md:items-center"><div className="h-64 min-h-0 w-full" aria-label="Gráfico circular de distribución patrimonial"><ResponsiveContainer width="100%" height="100%"><RechartsPieChart><Pie data={entries} dataKey="valueCents" nameKey="label" innerRadius={58} outerRadius={92} paddingAngle={2}>{entries.map(entry => <Cell key={entry.key} fill={entry.color} />)}</Pie><Tooltip formatter={(value: number) => money(value, currency)} /><Legend /></RechartsPieChart></ResponsiveContainer></div><div className="grid gap-2" aria-label="Detalle de la distribución patrimonial">{entries.map(entry => <div className="flex items-center justify-between gap-3 rounded-lg border border-border/60 px-3 py-2 text-sm" key={entry.key}><span className="flex min-w-0 items-center gap-2"><span className="size-2.5 shrink-0 rounded-full" style={{ backgroundColor: entry.color }} aria-hidden="true" /><span className="min-w-0 truncate">{entry.label}</span><span className="shrink-0 text-[10px] uppercase tracking-wide text-muted-foreground">{entry.kind === "asset" ? "Activo" : "Pasivo"}</span></span><strong className="shrink-0 tabular-nums">{money(entry.valueCents, currency)}</strong></div>)}</div></div>}</CardContent></Card>; }

function AssetList({ title, icon: Icon, items }: { title: string; icon: any; items: { id: number | string; name: string; subtitle: string; amount: string; state: string }[] }) { return <Card className="surface-card"><CardHeader><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-primary"/><CardTitle className="text-base">{title}</CardTitle></div></CardHeader><CardContent className="space-y-3">{items.length === 0 ? <p className="text-sm text-muted-foreground">Sin registros vigentes en este filtro.</p> : items.map(item => <div className="flex items-start justify-between gap-3" key={item.id}><div><p className="text-sm font-medium">{item.name}</p><p className="text-xs text-muted-foreground">{item.subtitle}</p></div><div className="text-right"><p className="text-sm font-medium">{item.amount}</p><Badge variant="secondary" className="text-[10px]">{item.state}</Badge></div></div>)}</CardContent></Card>; }
  function HistoryCard({ history, currency, scale, current, exportRows }: { history: any[]; currency: string; scale: number; current: LiveSummary; exportRows: PatrimonyHistoryExportRow[] }) { return <Card className="surface-card"><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><CardTitle className="text-base">Evolución manual</CardTitle><CardDescription>Snapshots de cierres mensuales y cálculo actual. Los cierres anteriores no cambian.</CardDescription></div><div className="flex shrink-0 flex-wrap gap-2"><Button type="button" size="sm" variant="outline" className="bg-background" disabled={!exportRows.length} onClick={() => exportPatrimonyHistory("csv", exportRows)}><Download className="mr-1.5 size-3.5" />CSV</Button><Button type="button" size="sm" variant="outline" className="bg-background" disabled={!exportRows.length} onClick={() => exportPatrimonyHistory("xlsx", exportRows)}><FileSpreadsheet className="mr-1.5 size-3.5" />Excel</Button></div></div></CardHeader><CardContent className="space-y-3"><div className="space-y-1.5 rounded-lg border border-primary/20 bg-primary/5 p-3"><div className="flex items-center justify-between gap-3 text-sm"><span className="font-medium">Actual · cuentas, activos y pasivos</span><strong>{money(current.netWorthCents, currency)}</strong></div><div className="h-1.5 overflow-hidden rounded-full bg-muted"><span className={current.netWorthCents >= 0 ? "block h-full rounded-full bg-emerald-600" : "block h-full rounded-full bg-rose-600"} style={{ width: `${Math.max(3, (Math.abs(current.netWorthCents) / scale) * 100)}%` }}/></div></div>{history.length === 0 ? <p className="text-sm text-muted-foreground">Aún no hay cierres mensuales guardados; el valor actual ya se muestra arriba.</p> : history.map(statement => { const positive = statement.netWorthCents >= 0; return <div key={statement.id} className="space-y-1.5"><div className="flex items-center justify-between gap-3 text-sm"><span>{new Date(statement.periodStart).toLocaleDateString("es-MX", { month: "short", year: "numeric" })}</span><strong>{money(statement.netWorthCents, currency)}</strong></div><div className="h-1.5 overflow-hidden rounded-full bg-muted"><span className={positive ? "block h-full rounded-full bg-emerald-600" : "block h-full rounded-full bg-rose-600"} style={{ width: `${Math.max(3, (Math.abs(statement.netWorthCents) / scale) * 100)}%` }}/></div></div>; })}<p className="rounded-md bg-muted/60 p-2 text-xs text-muted-foreground">El cálculo actual se actualiza al volver a consultar tus registros; no crea un cierre mensual ni modifica históricos. Las exportaciones incluyen únicamente esta evolución visible y el cálculo actual.</p></CardContent></Card>; }
