import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Building2, CheckCircle2, CircleDollarSign, Link2, Plus, ShieldCheck, UserRoundPlus } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { buildBaselineMetrics } from "@/lib/baselineMetrics";

function formatRate(rateMicros: number) { return (rateMicros / 1_000_000).toLocaleString("es-MX", { maximumFractionDigits: 6 }); }

export default function Workspace() {
  const utils = trpc.useUtils();
  const { data, isLoading } = trpc.finance.workspace.get.useQuery();
  const [entityOpen, setEntityOpen] = useState(false);
  const entitySave = trpc.finance.workspace.entitySave.useMutation({ onSuccess: async () => { await utils.finance.workspace.get.invalidate(); setEntityOpen(false); toast.success("Entidad guardada"); }, onError: error => toast.error(error.message) });
  const rateSave = trpc.finance.workspace.exchangeRateSave.useMutation({ onSuccess: async () => { await utils.finance.workspace.get.invalidate(); toast.success("Tipo de cambio manual guardado"); }, onError: error => toast.error(error.message) });
  const invite = trpc.finance.workspace.invite.useMutation({ onSuccess: async result => { await utils.finance.workspace.get.invalidate(); toast.success(result.message); }, onError: error => toast.error(error.message) });
  const revoke = trpc.finance.workspace.revokeInvite.useMutation({ onSuccess: async () => { await utils.finance.workspace.get.invalidate(); toast.success("Acceso revocado"); }, onError: error => toast.error(error.message) });
  const access = data?.workspaceAccess;
  const isOwner = access?.role === "owner";
  const activeEntities = useMemo(() => data?.entities.filter(entity => entity.status === "active") ?? [], [data?.entities]);
  const baseline = useMemo(() => buildBaselineMetrics(data ?? {}), [data]);
  if (isLoading) return <div className="page-loading">Cargando tu configuración privada…</div>;
  if (!data) return <div className="error-state"><h1>No se pudo cargar el espacio</h1><p>Intenta actualizar la página.</p></div>;
  return <div className="workspace-page space-y-7"><header className="page-heading"><div><p className="eyebrow">Fase A · espacio privado</p><h1>{data.profile?.workspaceName || "Configuración del espacio"}</h1><p>Gestiona entidades, proyectos, monedas y colaboración. Las cifras siguen siendo manuales y requieren confirmación humana.</p></div><span className="workspace-role"><ShieldCheck className="size-4" />{access?.role === "owner" ? "Propietaria" : access?.role === "manager" ? "Gestor con permisos" : "Revisor"}</span></header>
    <section className="workspace-summary"><article><Building2 /><div><small>Entidades activas</small><strong>{activeEntities.length}</strong><span>{data.entities.length} en total</span></div></article><article><CircleDollarSign /><div><small>Moneda base</small><strong>{data.profile?.currency}</strong><span>Política: {data.profile?.exchangeRatePolicy === "manual" ? "manual" : data.profile?.exchangeRatePolicy === "manual_confirmed" ? "manual confirmada" : "sin conversión"}</span></div></article><article><ShieldCheck /><div><small>Control</small><strong>{data.profile?.humanReviewRequired ? "Humano" : "Opcional"}</strong><span>Los borradores no se consolidan solos</span></div></article></section>
    <section className="content-card workspace-baseline"><div className="card-title-row"><div><h2>Línea base privada</h2><p>Inventario de cobertura para medir la evolución de tu uso personal. No es una calificación ni modifica datos.</p></div><span className="workspace-role"><CheckCircle2 className="size-4" /> Fase 0</span></div><div className="workspace-summary">{baseline.inventory.map(item => <article key={item.label}><div><small>{item.label}</small><strong>{item.value}</strong><span>{item.detail}</span></div></article>)}</div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{baseline.metrics.map(metric => <article key={metric.key} className="rounded-xl border border-border/70 bg-muted/20 p-3"><small className="text-muted-foreground">{metric.label}</small><strong className="mt-1 block text-xl">{metric.ratio === null ? "Sin datos" : `${metric.ratio}%`}</strong><span className="block text-xs text-muted-foreground">{metric.value}/{metric.total} · meta {metric.target}%</span></article>)}</div><p className="mt-4 text-sm text-muted-foreground">{baseline.privacy.humanReviewRequired ? "La revisión humana está activa." : "La revisión humana es opcional."} {baseline.privacy.personalProfileConsent ? "El perfil ampliado tiene consentimiento." : "El perfil ampliado sigue siendo opcional."} {baseline.privacy.openQualityIssues > 0 ? `${baseline.privacy.openQualityIssues} alertas de calidad requieren revisión.` : "No hay alertas de calidad abiertas."}</p></section>
    <section className="workspace-grid"><div className="content-card"><div className="card-title-row"><div><h2>Entidades</h2><p>País, forma legal, moneda funcional y estado operativo.</p></div>{isOwner && <Button size="sm" className="btn-primary" onClick={() => setEntityOpen(!entityOpen)}><Plus className="size-4" /> Añadir</Button>}</div>{entityOpen && <EntityForm defaultCurrency={data.profile?.currency || "MXN"} onSave={values => entitySave.mutate(values)} pending={entitySave.isPending} />}{data.entities.length === 0 ? <p className="workspace-empty">Aún no hay entidades configuradas.</p> : <div className="workspace-list">{data.entities.map(entity => <article key={entity.id}><div className="workspace-entity-icon"><Building2 className="size-4" /></div><div><strong>{entity.name}</strong><small>{entity.shortCode || "Sin código"} · {entity.countryCode} · {entity.legalForm.replaceAll("_", " ")}</small></div><div className="workspace-tag-group"><span className={`entity-status entity-${entity.status}`}>{entity.status === "active" ? "Activa" : entity.status === "planned" ? "Planeada" : "Inactiva"}</span><span>{entity.functionalCurrency}</span></div></article>)}</div>}</div>
      <div className="content-card"><div className="card-title-row"><div><h2>Proyectos financieros</h2><p>La gestión de proyectos, partes y tareas vive ahora en su propia sesión con vistas de lista, Kanban y calendario.</p></div></div><a className="inline-flex rounded-md border border-primary/20 px-3 py-2 text-sm font-semibold text-primary hover:bg-primary/5" href="/proyectos">Abrir Proyectos</a></div></section>
    <section className="workspace-grid"><div className="content-card"><div className="card-title-row"><div><h2>Tipos de cambio manuales</h2><p>Conserva el valor aplicado para reportar MXN, EUR o USD sin conversiones silenciosas.</p></div></div>{isOwner ? <ExchangeRateForm reportCurrency={data.profile?.currency || "MXN"} onSave={values => rateSave.mutate(values)} pending={rateSave.isPending} /> : null}<div className="workspace-list">{data.exchangeRates.length === 0 ? <p className="workspace-empty">No hay conversiones registradas. Las partidas en otra moneda quedarán pendientes de convertir.</p> : data.exchangeRates.slice().reverse().slice(0, 6).map(rate => <article key={rate.id}><div className="workspace-rate"><strong>{rate.fromCurrency} → {rate.toCurrency}</strong><small>{new Date(rate.rateDate).toLocaleDateString("es-MX")}</small></div><strong>{formatRate(rate.rateMicros)}</strong></article>)}</div></div>
      <div className="content-card"><div className="card-title-row"><div><h2>Gestor o contador</h2><p>Invita por correo. La persona debe registrarse y aceptar; no obtendrá propiedad ni acceso ilimitado.</p></div></div>{isOwner ? <InviteForm onSave={values => invite.mutate(values)} pending={invite.isPending} /> : null}<div className="workspace-list">{data.collaborators.length === 0 ? <p className="workspace-empty">Aún no hay personas invitadas.</p> : data.collaborators.map(person => <article key={person.id}><div className="workspace-entity-icon"><UserRoundPlus className="size-4" /></div><div><strong>{person.invitedEmail}</strong><small>{person.role === "manager" ? "Gestor" : "Revisor"} · {person.canCreateDrafts ? "puede crear borradores" : "sólo lectura/revisión"}</small></div><span className={`entity-status entity-${person.status}`}>{person.status === "accepted" ? "Aceptada" : person.status === "revoked" ? "Revocada" : "Invitada"}</span>{isOwner && person.status !== "revoked" ? <Button type="button" variant="ghost" size="sm" disabled={revoke.isPending} onClick={() => { if (confirm(`¿Revocar acceso a ${person.invitedEmail}?`)) revoke.mutate({ inviteId: person.id }); }}>Revocar</Button> : null}</article>)}</div></div></section>
    <section className="workspace-drive"><Link2 className="size-5" /><div><h2>Documentos sin duplicar archivos</h2><p>En Registros puedes pegar enlaces privados de Google Drive y etiquetarlos como referencia. Meximoney guarda el metadato y la URL; no copia el PDF ni solicita acceso a tu Drive en esta fase.</p></div></section>
  </div>;
}

function EntityForm({ defaultCurrency, onSave, pending }: { defaultCurrency: string; onSave: (values: any) => void; pending: boolean }) { const [form, setForm] = useState({ name: "", shortCode: "", countryCode: "MX", legalForm: "other", status: "planned", functionalCurrency: defaultCurrency, taxRegime: "not_applicable", notes: "" }); const submit = (event: FormEvent) => { event.preventDefault(); onSave({ ...form, shortCode: form.shortCode || null, notes: form.notes || null }); }; return <form className="workspace-form" onSubmit={submit}><Input required placeholder="Nombre de la entidad" value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} /><Input placeholder="Código" value={form.shortCode} onChange={event => setForm({ ...form, shortCode: event.target.value })} /><select value={form.countryCode} onChange={event => setForm({ ...form, countryCode: event.target.value })}><option value="MX">México</option><option value="ES">España</option><option value="US">Estados Unidos</option></select><select value={form.legalForm} onChange={event => setForm({ ...form, legalForm: event.target.value })}><option value="pfae">PFAE</option><option value="sa_de_cv">S.A. de C.V.</option><option value="sapi">S.A.P.I.</option><option value="sl">S.L.</option><option value="llc">LLC</option><option value="other">Otra</option></select><select value={form.status} onChange={event => setForm({ ...form, status: event.target.value })}><option value="active">Activa</option><option value="planned">Planeada</option><option value="inactive">Inactiva</option></select><Input maxLength={3} value={form.functionalCurrency} onChange={event => setForm({ ...form, functionalCurrency: event.target.value.toUpperCase() })} /><select value={form.taxRegime} onChange={event => setForm({ ...form, taxRegime: event.target.value })}><option value="pfae_general">PFAE general</option><option value="corporate">Sociedad</option><option value="other">Otro</option><option value="not_applicable">No aplica</option></select><Button type="submit" size="sm" disabled={pending}>Guardar entidad</Button></form>; }
function ProjectForm({ entities, onSave, pending }: { entities: any[]; onSave: (values: any) => void; pending: boolean }) { const [form, setForm] = useState({ name: "", entityId: entities[0]?.id?.toString() || "", status: "active", notes: "" }); const submit = (event: FormEvent) => { event.preventDefault(); onSave({ ...form, entityId: Number(form.entityId), notes: form.notes || null }); }; return <form className="workspace-form" onSubmit={submit}><Input required placeholder="Nombre del proyecto" value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} /><select required value={form.entityId} onChange={event => setForm({ ...form, entityId: event.target.value })}><option value="">Entidad</option>{entities.map(entity => <option key={entity.id} value={entity.id}>{entity.name}</option>)}</select><select value={form.status} onChange={event => setForm({ ...form, status: event.target.value })}><option value="active">Activo</option><option value="planned">Planeado</option><option value="paused">Pausado</option><option value="closed">Cerrado</option></select><Button type="submit" size="sm" disabled={pending}>Guardar proyecto</Button></form>; }
function ExchangeRateForm({ reportCurrency, onSave, pending }: { reportCurrency: string; onSave: (values: any) => void; pending: boolean }) { const [form, setForm] = useState({ fromCurrency: "EUR", toCurrency: reportCurrency, rate: "", rateDate: new Date().toISOString().slice(0, 10), source: "manual", notes: "" }); const submit = (event: FormEvent) => { event.preventDefault(); const rateMicros = Math.round(Number(form.rate) * 1_000_000); if (!Number.isFinite(rateMicros) || rateMicros < 1) return toast.error("Introduce un tipo de cambio válido."); onSave({ ...form, rateMicros, rateDate: new Date(`${form.rateDate}T12:00:00`).getTime(), notes: form.notes || null }); }; return <form className="workspace-form workspace-rate-form" onSubmit={submit}><Input maxLength={3} value={form.fromCurrency} onChange={event => setForm({ ...form, fromCurrency: event.target.value.toUpperCase() })} /><span>→</span><Input maxLength={3} value={form.toCurrency} onChange={event => setForm({ ...form, toCurrency: event.target.value.toUpperCase() })} /><Input required type="number" min="0.000001" step="0.000001" placeholder="Ej. 18.42" value={form.rate} onChange={event => setForm({ ...form, rate: event.target.value })} /><Input required type="date" value={form.rateDate} onChange={event => setForm({ ...form, rateDate: event.target.value })} /><Button type="submit" size="sm" disabled={pending}>Guardar tipo</Button></form>; }
function InviteForm({ onSave, pending }: { onSave: (values: any) => void; pending: boolean }) { const [form, setForm] = useState({ email: "", role: "reviewer", canCreateDrafts: false, canReview: true }); const submit = (event: FormEvent) => { event.preventDefault(); onSave(form); }; return <form className="workspace-form workspace-invite-form" onSubmit={submit}><Input required type="email" placeholder="gestor@ejemplo.com" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} /><select value={form.role} onChange={event => setForm({ ...form, role: event.target.value })}><option value="reviewer">Revisor</option><option value="manager">Gestor</option></select><label><input type="checkbox" checked={form.canCreateDrafts} onChange={event => setForm({ ...form, canCreateDrafts: event.target.checked })} /> Puede crear borradores</label><label><input type="checkbox" checked={form.canReview} onChange={event => setForm({ ...form, canReview: event.target.checked })} /> Puede revisar</label><Button type="submit" size="sm" disabled={pending}>Crear invitación</Button></form>; }
