import { Button } from "@/components/ui/button";
import { buildAmortizationSummary, exportAmortization, type AmortizationAdjustment, type AmortizationDebt, type AmortizationPayment, type AmortizationProjection } from "@/lib/amortizationExport";
import { FileDown, FileSpreadsheet, PieChart as PieChartIcon } from "lucide-react";
import { Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip } from "recharts";

const money = (value: number, currency: string) => new Intl.NumberFormat("es-MX", { style: "currency", currency, minimumFractionDigits: 2 }).format(value / 100);

export function AmortizationInsights({ debt, payments, projection, adjustments }: { debt: AmortizationDebt; payments: AmortizationPayment[]; projection: AmortizationProjection; adjustments: AmortizationAdjustment[] }) {
  const summary = buildAmortizationSummary(debt, payments);
  const chart = [
    { name: "Capital pagado", value: summary.capitalPaidCents, color: "#00796b" },
    { name: "Interés ordinario", value: summary.regularInterestPaidCents, color: "#5c6bc0" },
    { name: "Interés vencido", value: summary.lateInterestPaidCents, color: "#d97706" },
  ].filter(item => item.value > 0);
  return <section className="space-y-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><h3 className="text-sm font-semibold">Resumen de amortización</h3><p className="mt-1 text-xs text-muted-foreground">Sólo contabiliza cuotas conciliadas. La proyección no se mezcla con pagos reales.</p></div><div className="flex flex-wrap gap-2"><Button type="button" size="sm" variant="outline" onClick={() => exportAmortization("xlsx", debt, payments, projection, adjustments)}><FileSpreadsheet className="mr-1.5 size-4"/>Excel</Button><Button type="button" size="sm" variant="outline" onClick={() => exportAmortization("pdf", debt, payments, projection, adjustments)}><FileDown className="mr-1.5 size-4"/>PDF</Button></div></div><div className="grid grid-cols-1 gap-3 md:grid-cols-3"><Summary label="Capital pagado" value={summary.capitalPaidCents} currency={debt.currency} tone="text-emerald-700"/><Summary label="Intereses pagados" value={summary.totalInterestPaidCents} currency={debt.currency} tone="text-amber-700"/><Summary label="Capital restante" value={summary.capitalRemainingCents} currency={debt.currency} tone="text-primary"/></div><div className="rounded-xl border border-border/70 bg-muted/20 p-3"><div className="flex items-center gap-2"><PieChartIcon className="size-4 text-primary"/><div><h4 className="text-sm font-semibold">Proporción de capital e intereses pagados</h4><p className="text-xs text-muted-foreground">El interés ordinario y vencido se distinguen para facilitar la revisión.</p></div></div>{chart.length ? <div className="mt-2 h-52"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={chart} dataKey="value" nameKey="name" innerRadius={52} outerRadius={78} paddingAngle={3}>{chart.map(item => <Cell key={item.name} fill={item.color}/>)}</Pie><Tooltip formatter={(value: number) => money(Number(value), debt.currency)}/><Legend iconType="circle" iconSize={8}/></PieChart></ResponsiveContainer></div> : <p className="py-8 text-center text-sm text-muted-foreground">Aún no hay pagos conciliados para calcular la proporción.</p>}</div></section>;
}

function Summary({ label, value, currency, tone }: { label: string; value: number; currency: string; tone: string }) { return <div className="rounded-xl border border-border/70 bg-background p-3"><p className="text-xs text-muted-foreground">{label}</p><p className={`mt-1 text-lg font-semibold ${tone}`}>{money(value, currency)}</p></div>; }
