import { AmortizationInsights } from "@/components/AmortizationInsights";
import { Button } from "@/components/ui/button";
import { DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { amortizationDialogClass } from "@/lib/amortizationDialogLayout";
import { formatDate, formatMoney, toCents } from "@/lib/finance";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, Maximize2, Minimize2, Trash2 } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { toast } from "sonner";

export function PlanningDebtAmortizationDialog({ debt, onChanged }: { debt: any; onChanged: () => void | Promise<void> }) {
  const utils = trpc.useUtils();
  const { data, isLoading } = trpc.finance.debts.amortization.useQuery({ debtId: debt.id });
  const chargeSave = trpc.finance.debts.adjustmentSave.useMutation({ onSuccess: async () => { await utils.finance.debts.amortization.invalidate({ debtId: debt.id }); await onChanged(); toast.success("Cargo manual guardado y saldo actualizado."); }, onError: error => toast.error(error.message) });
  const chargeRemove = trpc.finance.debts.adjustmentRemove.useMutation({ onSuccess: async () => { await utils.finance.debts.amortization.invalidate({ debtId: debt.id }); await onChanged(); toast.success("Cargo manual eliminado."); }, onError: error => toast.error(error.message) });
  const [form, setForm] = useState({ type: "late_interest", amount: "", occurredAt: new Date().toISOString().slice(0, 10), notes: "" });
  const [expanded, setExpanded] = useState(false);
  const dialogClass = `${amortizationDialogClass(expanded)} [&_[data-slot=dialog-close]]:right-3 [&_[data-slot=dialog-close]]:top-3 [&_[data-slot=dialog-close]]:z-30 [&_[data-slot=dialog-close]]:rounded-md [&_[data-slot=dialog-close]]:bg-background/95 [&_[data-slot=dialog-close]]:p-1 [&_[data-slot=dialog-close]]:shadow-sm`;
  const expandLabel = expanded ? "Reducir" : "Ampliar";
  const submitCharge = (event: FormEvent) => { event.preventDefault(); chargeSave.mutate({ debtId: debt.id, type: form.type as any, amountCents: toCents(form.amount), currency: debt.currency, occurredAt: new Date(`${form.occurredAt}T12:00:00`).getTime(), notes: form.notes || null }); };
  useEffect(() => {
    if (!debt.focusCharges || isLoading || !data) return;
    document.getElementById("debt-adjustment-form")?.scrollIntoView({ behavior: "smooth", block: "center" });
  }, [data, debt.focusCharges, isLoading]);

  return <DialogContent className={dialogClass}>
    <Button type="button" size="sm" variant="outline" className="absolute right-12 top-3 z-30 h-8 gap-1.5 bg-background/95 px-2 shadow-sm" aria-label={`${expandLabel} ventana de amortización`} aria-pressed={expanded} title={expandLabel} onClick={() => setExpanded(value => !value)}>
      {expanded ? <Minimize2 className="size-3.5"/> : <Maximize2 className="size-3.5"/>}
      <span className="hidden sm:inline">{expandLabel}</span>
    </Button>
    <DialogHeader className="sticky top-0 z-20 -mx-4 -mt-4 border-b border-border/80 bg-background/95 px-4 pb-4 pt-4 pr-28 text-left backdrop-blur-sm sm:-mx-6 sm:-mt-6 sm:px-6 sm:pb-5 sm:pt-6 sm:pr-32">
      <p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-primary">Deuda y financiación</p>
      <DialogTitle className="text-xl leading-tight tracking-tight sm:text-2xl">Amortización de {debt.name}</DialogTitle>
      <DialogDescription className="max-w-3xl text-xs leading-relaxed sm:text-sm">Consulta y registro manual. La proyección no modifica pagos, intereses o cargos.</DialogDescription>
    </DialogHeader>
    {isLoading || !data ? <p className="py-8 text-sm text-muted-foreground">Preparando tabla…</p> : <div className="min-w-0 space-y-6 pb-2">
      <AmortizationInsights debt={data.debt} payments={data.payments} projection={data.projection} adjustments={data.adjustments}/>
      <div className="rounded-2xl border border-primary/15 bg-primary/5 p-4 text-sm text-muted-foreground"><strong className="text-foreground">Saldo actual:</strong> {formatMoney(data.debt.balanceCents, data.debt.currency)}. Los intereses vencidos, cargos y correcciones sólo se reflejan si tú los capturas desde el estado de cuenta o contrato.</div>
      <div className="grid min-w-0 gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(0,1fr)]">
        <section className="min-w-0"><h3 className="mb-2 text-sm font-semibold">Cuotas conciliadas</h3><div className="max-h-[min(46dvh,30rem)] overflow-auto rounded-xl border" aria-label="Tabla de cuotas conciliadas"><table className="w-full min-w-[620px] whitespace-nowrap text-sm"><thead className="sticky top-0 z-10 bg-muted/95 text-left text-xs text-muted-foreground shadow-sm"><tr><th className="p-2">Fecha</th><th className="p-2 text-right">Total</th><th className="p-2 text-right">Capital</th><th className="p-2 text-right">Interés</th><th className="p-2 text-right">Vencido</th><th className="p-2 text-right">Cargos</th></tr></thead><tbody>{data.payments.length ? data.payments.map((item: any) => <tr className="border-t" key={item.id}><td className="p-2">{formatDate(item.paidAt)}</td><td className="p-2 text-right">{formatMoney(item.totalPaymentCents, data.debt.currency)}</td><td className="p-2 text-right">{formatMoney(item.principalCents, data.debt.currency)}</td><td className="p-2 text-right">{formatMoney(item.interestCents, data.debt.currency)}</td><td className="p-2 text-right">{formatMoney(item.lateInterestCents, data.debt.currency)}</td><td className="p-2 text-right">{formatMoney(item.feeCents, data.debt.currency)}</td></tr>) : <tr><td colSpan={6} className="p-5 text-center whitespace-normal text-muted-foreground">Sin cuotas conciliadas todavía.</td></tr>}</tbody></table></div></section>
        <section className="min-w-0"><h3 className="mb-2 text-sm font-semibold">Intereses y cargos manuales</h3><div className="space-y-2">{data.adjustments.length ? data.adjustments.map((item: any) => <div className="flex items-center justify-between gap-3 rounded-lg border p-3 text-sm" key={item.id}><span><strong>{item.type === "late_interest" ? "Interés vencido" : item.type === "finance_charge" ? "Cargo financiero" : item.type === "other_charge" ? "Otro cargo" : "Corrección"}</strong><small className="mt-1 block text-muted-foreground">{formatDate(item.occurredAt)}{item.notes ? ` · ${item.notes}` : ""}</small></span><span className="flex items-center gap-2"><strong>{formatMoney(item.amountCents, data.debt.currency)}</strong><Button type="button" size="icon" variant="ghost" aria-label="Eliminar cargo manual" onClick={() => { if (confirm("¿Eliminar este cargo? Sólo se permite si el saldo sigue siendo coherente.")) chargeRemove.mutate({ id: item.id }); }}><Trash2 className="size-4 text-muted-foreground" /></Button></span></div>) : <p className="rounded-xl border border-dashed p-4 text-sm text-muted-foreground">No hay cargos manuales registrados.</p>}</div><form id="debt-adjustment-form" className="mt-3 grid gap-2 rounded-xl border p-3" onSubmit={submitCharge}><p className="text-sm font-semibold">Registrar cargo confirmado</p><div className="grid gap-2 sm:grid-cols-3"><select value={form.type} onChange={event => setForm({ ...form, type: event.target.value })}><option value="late_interest">Interés vencido</option><option value="finance_charge">Cargo financiero</option><option value="other_charge">Otro cargo</option><option value="correction">Corrección de saldo</option></select><Input required type="number" min={form.type === "correction" ? undefined : "0.01"} step="0.01" placeholder="Importe" value={form.amount} onChange={event => setForm({ ...form, amount: event.target.value })}/><Input required type="date" value={form.occurredAt} onChange={event => setForm({ ...form, occurredAt: event.target.value })}/></div><Textarea placeholder="Referencia del estado de cuenta o contrato" value={form.notes} onChange={event => setForm({ ...form, notes: event.target.value })}/><Button type="submit" size="sm" variant="outline" disabled={chargeSave.isPending || !form.amount}>{chargeSave.isPending ? "Guardando…" : "Guardar cargo manual"}</Button></form></section>
      </div>
      <section className="min-w-0"><div className="mb-2 flex flex-col gap-1 sm:flex-row sm:items-end sm:justify-between"><div><h3 className="text-sm font-semibold">Escenario de amortización</h3><p className="text-xs text-muted-foreground">Usa la tasa y pago mensual de referencia de la deuda. No incluye futuros atrasos ni cargos.</p></div><span className="text-sm font-medium">Interés proyectado: {formatMoney(data.projection.totalProjectedInterestCents, data.debt.currency)}</span></div>{data.projection.warning ? <div className="mb-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-950"><AlertTriangle className="mr-2 inline size-4"/>{data.projection.warning}</div> : null}<div className="max-h-[min(46dvh,30rem)] overflow-auto rounded-xl border" aria-label="Tabla de amortización proyectada"><table className="w-full min-w-[640px] whitespace-nowrap text-sm"><thead className="sticky top-0 z-10 bg-muted/95 text-left text-xs text-muted-foreground shadow-sm"><tr><th className="p-2">Cuota</th><th className="p-2 text-right">Saldo inicial</th><th className="p-2 text-right">Interés ordinario</th><th className="p-2 text-right">Pago ref.</th><th className="p-2 text-right">Capital</th><th className="p-2 text-right">Saldo final</th></tr></thead><tbody>{data.projection.rows.length ? data.projection.rows.map((row: any) => <tr className="border-t" key={row.installment}><td className="p-2">{row.installment}</td><td className="p-2 text-right">{formatMoney(row.openingBalanceCents, data.debt.currency)}</td><td className="p-2 text-right">{formatMoney(row.regularInterestCents, data.debt.currency)}</td><td className="p-2 text-right">{formatMoney(row.plannedPaymentCents, data.debt.currency)}</td><td className="p-2 text-right">{formatMoney(row.principalCents, data.debt.currency)}</td><td className="p-2 text-right">{formatMoney(row.closingBalanceCents, data.debt.currency)}</td></tr>) : <tr><td colSpan={6} className="p-5 text-center whitespace-normal text-muted-foreground">Completa el pago mensual de referencia para proyectar cuotas.</td></tr>}</tbody></table></div></section>
    </div>}
  </DialogContent>;
}
